spring:
  application:
    name: server-springboot
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/ams_db}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:3223}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
jwt:
  signerKey: "fc9c59bd385c1c0682de9ce04d4f5a9ab4b783bd4c4f22c8b91ce5808b2a65e7"
  valid-duration: 3600 # in second
  refreshable-duration: 72000 #seconds